-- MySQL Script generated by MySQL Workbench
-- Wed Jun 17 21:30:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema beentheredb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `beentheredb` ;

-- -----------------------------------------------------
-- Schema beentheredb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beentheredb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `beentheredb` ;

-- -----------------------------------------------------
-- Table `beentheredb`.`accountToProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`accountToProfile` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`accountToProfile` (
  `accounts_UID` INT NULL DEFAULT NULL,
  `profile_PID` INT NOT NULL,
  UNIQUE INDEX `accounts_UID_UNIQUE` (`accounts_UID` ASC) VISIBLE,
  UNIQUE INDEX `profile_PID_UNIQUE` (`profile_PID` ASC) VISIBLE,
  INDEX `fk_accountToProfile_accounts_idx` (`accounts_UID` ASC) VISIBLE,
  INDEX `fk_accountToProfile_profile1_idx` (`profile_PID` ASC) VISIBLE,
  CONSTRAINT `fk_accountToProfile_accounts`
    FOREIGN KEY (`accounts_UID`)
    REFERENCES `beentheredb`.`accounts` (`UID`),
  CONSTRAINT `fk_accountToProfile_profile1`
    FOREIGN KEY (`profile_PID`)
    REFERENCES `beentheredb`.`profile` (`PID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`accountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`accountType` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`accountType` (
  `admin_adminID` INT NOT NULL,
  `mentee_menteeID` INT NOT NULL,
  `mentor_mentorID` INT NOT NULL,
  `profile_PID` INT NOT NULL,
  PRIMARY KEY (`admin_adminID`, `mentee_menteeID`, `mentor_mentorID`, `profile_PID`),
  INDEX `fk_accountType_admin1_idx` (`admin_adminID` ASC) VISIBLE,
  INDEX `fk_accountType_mentee1_idx` (`mentee_menteeID` ASC) VISIBLE,
  INDEX `fk_accountType_mentor1_idx` (`mentor_mentorID` ASC) VISIBLE,
  INDEX `fk_accountType_profile1_idx` (`profile_PID` ASC) VISIBLE,
  UNIQUE INDEX `profile_PID_UNIQUE` (`profile_PID` ASC) VISIBLE,
  CONSTRAINT `fk_accountType_admin1`
    FOREIGN KEY (`admin_adminID`)
    REFERENCES `beentheredb`.`admin` (`adminID`),
  CONSTRAINT `fk_accountType_mentee1`
    FOREIGN KEY (`mentee_menteeID`)
    REFERENCES `beentheredb`.`mentee` (`menteeID`),
  CONSTRAINT `fk_accountType_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`),
  CONSTRAINT `fk_accountType_profile1`
    FOREIGN KEY (`profile_PID`)
    REFERENCES `beentheredb`.`profile` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`accounts` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`accounts` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `phoneNumber` INT NULL DEFAULT NULL,
  `emailAddress` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `uid_UNIQUE` (`UID` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `Email Address_UNIQUE` (`emailAddress` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`admin` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`admin` (
  `adminID` INT NOT NULL DEFAULT 0,
  `info` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`adminID`),
  UNIQUE INDEX `adminID_UNIQUE` (`adminID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`chat` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`chat` (
  `chatID` INT NOT NULL AUTO_INCREMENT,
  `chatPath` VARCHAR(255) NOT NULL,
  `chatRating` FLOAT NOT NULL,
  `TimeStamp` DATETIME NOT NULL,
  PRIMARY KEY (`chatID`),
  UNIQUE INDEX `chatID_UNIQUE` (`chatID` ASC) VISIBLE,
  UNIQUE INDEX `chatPath_UNIQUE` (`chatPath` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`chatRelations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`chatRelations` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`chatRelations` (
  `mentee_menteeID` INT NOT NULL,
  `mentor_mentorID` INT NOT NULL,
  `chat_chatID` INT NOT NULL,
  PRIMARY KEY (`mentee_menteeID`, `mentor_mentorID`, `chat_chatID`),
  UNIQUE INDEX `chat_chatID_UNIQUE` (`chat_chatID` ASC) VISIBLE,
  INDEX `fk_chatRelation_mentee1_idx` (`mentee_menteeID` ASC) VISIBLE,
  INDEX `fk_chatRelation_mentor1_idx` (`mentor_mentorID` ASC) VISIBLE,
  INDEX `fk_chatRelations_chat1_idx` (`chat_chatID` ASC) VISIBLE,
  CONSTRAINT `fk_chatRelation_mentee1`
    FOREIGN KEY (`mentee_menteeID`)
    REFERENCES `beentheredb`.`mentee` (`menteeID`),
  CONSTRAINT `fk_chatRelation_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`),
  CONSTRAINT `fk_chatRelations_chat1`
    FOREIGN KEY (`chat_chatID`)
    REFERENCES `beentheredb`.`chat` (`chatID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`medal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`medal` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`medal` (
  `medal1` TINYINT(1) NOT NULL DEFAULT '0',
  `medal2` TINYINT(1) NOT NULL DEFAULT '0',
  `mentor_mentorID` INT NOT NULL,
  PRIMARY KEY (`mentor_mentorID`),
  UNIQUE INDEX `mentor_mentorID_UNIQUE` (`mentor_mentorID` ASC) VISIBLE,
  INDEX `fk_medal_mentor1_idx` (`mentor_mentorID` ASC) VISIBLE,
  CONSTRAINT `fk_medal_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`mentee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`mentee` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`mentee` (
  `menteeID` INT NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`menteeID`),
  UNIQUE INDEX `menteeID_UNIQUE` (`menteeID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`mentor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`mentor` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`mentor` (
  `mentorID` INT NOT NULL AUTO_INCREMENT,
  `descriptionPath` VARCHAR(255) NOT NULL,
  `storyPath` VARCHAR(255) NOT NULL,
  `videoPath` VARCHAR(255) NOT NULL,
  `photosPath` VARCHAR(255) NOT NULL,
  `rating` FLOAT NOT NULL DEFAULT 5,
  `price` FLOAT NOT NULL DEFAULT 0,
  `numberConsultations` INT NOT NULL DEFAULT 0,
  `audioDesPath` VARCHAR(255) NOT NULL,
  `balance` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`mentorID`),
  UNIQUE INDEX `audioDesPath_UNIQUE` (`audioDesPath` ASC) VISIBLE,
  UNIQUE INDEX `photosPath_UNIQUE` (`photosPath` ASC) VISIBLE,
  UNIQUE INDEX `videoPath_UNIQUE` (`videoPath` ASC) VISIBLE,
  UNIQUE INDEX `storyPath_UNIQUE` (`storyPath` ASC) VISIBLE,
  UNIQUE INDEX `descriptionPath_UNIQUE` (`descriptionPath` ASC) VISIBLE,
  UNIQUE INDEX `mentorID_UNIQUE` (`mentorID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`profile` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`profile` (
  `PID` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(255) NOT NULL,
  `wechat` VARCHAR(20) NULL,
  `birthday` DATETIME NULL,
  `picurePath` VARCHAR(255) NULL DEFAULT NULL,
  `program` VARCHAR(255) NULL,
  `school` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  PRIMARY KEY (`PID`),
  UNIQUE INDEX `PID_UNIQUE` (`PID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `beentheredb`.`thanksCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `beentheredb`.`thanksCard` ;

CREATE TABLE IF NOT EXISTS `beentheredb`.`thanksCard` (
  `cardID` INT NOT NULL AUTO_INCREMENT,
  `mentee_menteeID` INT NOT NULL,
  `mentor_mentorID` INT NOT NULL,
  `cardcontent` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cardID`),
  UNIQUE INDEX `cardID_UNIQUE` (`cardID` ASC) VISIBLE,
  INDEX `fk_thanksCard_mentee1_idx` (`mentee_menteeID` ASC) VISIBLE,
  INDEX `fk_thanksCard_mentor1_idx` (`mentor_mentorID` ASC) VISIBLE,
  CONSTRAINT `fk_thanksCard_mentee1`
    FOREIGN KEY (`mentee_menteeID`)
    REFERENCES `beentheredb`.`mentee` (`menteeID`),
  CONSTRAINT `fk_thanksCard_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
