-- MySQL Script generated by MySQL Workbench
-- Sun Jun 21 23:28:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema beentheredb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema beentheredb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `beentheredb` DEFAULT CHARACTER SET latin1 ;
USE `beentheredb` ;

-- -----------------------------------------------------
-- Table `beentheredb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`accounts` (
  `UID` INT(11) NOT NULL AUTO_INCREMENT,
  `phoneNumber` INT(11) NULL DEFAULT NULL,
  `emailAddress` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `uid_UNIQUE` (`UID` ASC),
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC),
  UNIQUE INDEX `Email Address_UNIQUE` (`emailAddress` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`profile` (
  `PID` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL,
  `wechat` VARCHAR(20) NULL DEFAULT NULL,
  `birthday` DATETIME NULL DEFAULT NULL,
  `picurePath` VARCHAR(255) NULL DEFAULT NULL,
  `program` VARCHAR(255) NULL DEFAULT NULL,
  `school` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`PID`),
  UNIQUE INDEX `PID_UNIQUE` (`PID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`accountToProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`accountToProfile` (
  `accounts_UID` INT(11) NULL DEFAULT NULL,
  `profile_PID` INT(11) NOT NULL,
  UNIQUE INDEX `profile_PID_UNIQUE` (`profile_PID` ASC),
  UNIQUE INDEX `accounts_UID_UNIQUE` (`accounts_UID` ASC),
  INDEX `fk_accountToProfile_accounts_idx` (`accounts_UID` ASC),
  INDEX `fk_accountToProfile_profile1_idx` (`profile_PID` ASC),
  CONSTRAINT `fk_accountToProfile_accounts`
    FOREIGN KEY (`accounts_UID`)
    REFERENCES `beentheredb`.`accounts` (`UID`),
  CONSTRAINT `fk_accountToProfile_profile1`
    FOREIGN KEY (`profile_PID`)
    REFERENCES `beentheredb`.`profile` (`PID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`admin` (
  `adminID` INT(11) NOT NULL DEFAULT '0',
  `info` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`adminID`),
  UNIQUE INDEX `adminID_UNIQUE` (`adminID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`mentee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`mentee` (
  `menteeID` INT(11) NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`menteeID`),
  UNIQUE INDEX `menteeID_UNIQUE` (`menteeID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`mentor` (
  `mentorID` INT(11) NOT NULL AUTO_INCREMENT,
  `descriptionPath` VARCHAR(255) NOT NULL,
  `storyPath` VARCHAR(255) NOT NULL,
  `videoPath` VARCHAR(255) NOT NULL,
  `photosPath` VARCHAR(255) NOT NULL,
  `rating` FLOAT NOT NULL DEFAULT '5',
  `price` FLOAT NOT NULL DEFAULT '0',
  `numberConsultations` INT(11) NOT NULL DEFAULT '0',
  `audioDesPath` VARCHAR(255) NOT NULL,
  `balance` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`mentorID`),
  UNIQUE INDEX `audioDesPath_UNIQUE` (`audioDesPath` ASC),
  UNIQUE INDEX `photosPath_UNIQUE` (`photosPath` ASC),
  UNIQUE INDEX `videoPath_UNIQUE` (`videoPath` ASC),
  UNIQUE INDEX `storyPath_UNIQUE` (`storyPath` ASC),
  UNIQUE INDEX `descriptionPath_UNIQUE` (`descriptionPath` ASC),
  UNIQUE INDEX `mentorID_UNIQUE` (`mentorID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`accountType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`accountType` (
  `admin_adminID` INT(11) NOT NULL,
  `mentee_menteeID` INT(11) NOT NULL,
  `mentor_mentorID` INT(11) NOT NULL,
  `profile_PID` INT(11) NOT NULL,
  PRIMARY KEY (`admin_adminID`, `mentee_menteeID`, `mentor_mentorID`, `profile_PID`),
  UNIQUE INDEX `profile_PID_UNIQUE` (`profile_PID` ASC),
  INDEX `fk_accountType_admin1_idx` (`admin_adminID` ASC),
  INDEX `fk_accountType_mentee1_idx` (`mentee_menteeID` ASC),
  INDEX `fk_accountType_mentor1_idx` (`mentor_mentorID` ASC),
  INDEX `fk_accountType_profile1_idx` (`profile_PID` ASC),
  CONSTRAINT `fk_accountType_admin1`
    FOREIGN KEY (`admin_adminID`)
    REFERENCES `beentheredb`.`admin` (`adminID`),
  CONSTRAINT `fk_accountType_mentee1`
    FOREIGN KEY (`mentee_menteeID`)
    REFERENCES `beentheredb`.`mentee` (`menteeID`),
  CONSTRAINT `fk_accountType_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`),
  CONSTRAINT `fk_accountType_profile1`
    FOREIGN KEY (`profile_PID`)
    REFERENCES `beentheredb`.`profile` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`chat` (
  `chatID` INT(11) NOT NULL AUTO_INCREMENT,
  `chatPath` VARCHAR(255) NOT NULL,
  `chatRating` FLOAT NOT NULL,
  `TimeStamp` DATETIME NOT NULL,
  PRIMARY KEY (`chatID`),
  UNIQUE INDEX `chatID_UNIQUE` (`chatID` ASC),
  UNIQUE INDEX `chatPath_UNIQUE` (`chatPath` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`chatRelations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`chatRelations` (
  `mentee_menteeID` INT(11) NOT NULL,
  `mentor_mentorID` INT(11) NOT NULL,
  `chat_chatID` INT(11) NOT NULL,
  PRIMARY KEY (`mentee_menteeID`, `mentor_mentorID`, `chat_chatID`),
  UNIQUE INDEX `chat_chatID_UNIQUE` (`chat_chatID` ASC),
  INDEX `fk_chatRelation_mentee1_idx` (`mentee_menteeID` ASC),
  INDEX `fk_chatRelation_mentor1_idx` (`mentor_mentorID` ASC),
  INDEX `fk_chatRelations_chat1_idx` (`chat_chatID` ASC),
  CONSTRAINT `fk_chatRelation_mentee1`
    FOREIGN KEY (`mentee_menteeID`)
    REFERENCES `beentheredb`.`mentee` (`menteeID`),
  CONSTRAINT `fk_chatRelation_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`),
  CONSTRAINT `fk_chatRelations_chat1`
    FOREIGN KEY (`chat_chatID`)
    REFERENCES `beentheredb`.`chat` (`chatID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`medal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`medal` (
  `medal1` TINYINT(1) NOT NULL DEFAULT '0',
  `medal2` TINYINT(1) NOT NULL DEFAULT '0',
  `mentor_mentorID` INT(11) NOT NULL,
  PRIMARY KEY (`mentor_mentorID`),
  UNIQUE INDEX `mentor_mentorID_UNIQUE` (`mentor_mentorID` ASC),
  INDEX `fk_medal_mentor1_idx` (`mentor_mentorID` ASC),
  CONSTRAINT `fk_medal_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `beentheredb`.`thanksCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `beentheredb`.`thanksCard` (
  `cardID` INT(11) NOT NULL AUTO_INCREMENT,
  `mentee_menteeID` INT(11) NOT NULL,
  `mentor_mentorID` INT(11) NOT NULL,
  `cardcontent` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cardID`),
  UNIQUE INDEX `cardID_UNIQUE` (`cardID` ASC),
  INDEX `fk_thanksCard_mentee1_idx` (`mentee_menteeID` ASC),
  INDEX `fk_thanksCard_mentor1_idx` (`mentor_mentorID` ASC),
  CONSTRAINT `fk_thanksCard_mentee1`
    FOREIGN KEY (`mentee_menteeID`)
    REFERENCES `beentheredb`.`mentee` (`menteeID`),
  CONSTRAINT `fk_thanksCard_mentor1`
    FOREIGN KEY (`mentor_mentorID`)
    REFERENCES `beentheredb`.`mentor` (`mentorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
