export default {
  "theme-color-primary": "#FFF2DF",
  "theme-color-primary-2": "#Ffebce",
  "theme-color-secondary": "#EBf2FF",
  "theme-color-secondary-2": "#dbe3ff",
  "theme-color-secondary-3": "#a6bbff",
  "theme-color-tertiary": "#F0F0FF",
  "theme-color-tertiary-2": "#dedeff",
  "theme-color-tertiary-3": "#9c9cff",
  "button-color": "#ffe6c1",
  "font-color-light-1": "#787878",
  "font-color-light-2": "#A5A5A5",
  "font-color-dark": "#656565",
  "font-size-ss": ".8rem",
  "font-size-s": "1.2rem",
  "font-size-m": "1.4rem",
  "font-size-l": "1.6rem",
  "font-size-ls": "2rem",
  "font-size-ll": "3rem",
  "line-height-ll": "160%",
  "line-height-l": "140%",
  "line-height-m": "130%",
  "line-height-s": "120%",
  "line-height-ss": "18px",
  // "border-color": "#FFC368",
  "highlight-color": "#FBD193",
  "background-color-white": "#fdfdfd",
  // "background-color-yellow-1": "#fff2df",
  "background-color-yellow-2": "#fff5e6",
  "color-yellow-3": "#fefbf6",
  "background-color-grey": "#f9f9f9",
};
